# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
default:
  image:
    name: gjrtimmer/docker:latest
    pull_policy: always
  interruptible: false

include:
  - project: templates/ci
    file: default.yml

amd64:
  extends: .docker-build-amd64
  interruptible: false
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:amd64

arm64:
  extends: .docker-build-arm64
  interruptible: false
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:arm64

multi:
  extends: .docker-build-multi
  interruptible: false
  needs:
    - amd64
    - arm64
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
      --cache-from=type=registry,ref=${DOCKER_IMAGE_PATH}:amd64
      --cache-from=type=registry,ref=${DOCKER_IMAGE_PATH}:arm64
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:latest
