stages:
  - build
  - deploy

include:
  - project: templates/ci
    file:
      - docker.yml
      - docker-auth.yml
      - docker-hub.yml
      - docker-multi-arch.yml

build:
  extends: .docker-multi-arch-build

dockerhub:
  stage: deploy
  extends:
    - .docker-multi-arch-build
    - .dockerhub-auth
  variables:
    DOCKER_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest
  only:
    - main
    - schedules
