# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
default:
  image:
    name: $DOCKER_HUB_PROXY/docker:27.3.1-cli
    pull_policy: always
  interruptible: false

variables:
  TARGET_LIVE: $HARBOR_REGISTRY_LIVE/docker

include:
  - component: $CI_SERVER_FQDN/templates/components/workflow/default@0.4.0
  - component: $CI_SERVER_FQDN/templates/components/publish/live@0.7.0
  - component: $CI_SERVER_FQDN/templates/components/publish/hub@0.7.0
  - component: $CI_SERVER_FQDN/templates/components/renovate/renovate@0.9.0
  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.9.0
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
    inputs:
      interruptible: false
      args: >-
        --build-context=gitlab=/builds/$CI_PROJECT_PATH.tmp
  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.9.0
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      name: release
      interruptible: false
      cache: false
      args: >-
        --build-context=gitlab=/builds/$CI_PROJECT_PATH.tmp
      tag: $HARBOR_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_TAG
      tags: >-
        --tag=$HARBOR_REGISTRY_LIVE/$CI_PROJECT_PATH:$CI_COMMIT_TAG
