# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
default:
  image:
    name: gjrtimmer/docker:latest
    pull_policy: always
  interruptible: false

include:
  - project: templates/ci
    file: default.yml

amd64:
  extends: .docker-build-amd64
  interruptible: false
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:amd64
    HEALTH_CHECK_UUID: cd8b11c8-8ec5-45a1-89b1-495c51d6c4aa

arm64:
  extends: .docker-build-arm64
  interruptible: false
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:arm64
    HEALTH_CHECK_UUID: 23310f5b-19c1-47aa-a94b-66722cec170e

multi:
  extends: .docker-build-multi
  interruptible: false
  needs:
    - amd64
    - arm64
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
      --cache-from=type=registry,ref=${DOCKER_IMAGE_PATH}:amd64
      --cache-from=type=registry,ref=${DOCKER_IMAGE_PATH}:arm64
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:latest
    HEALTH_CHECK_UUID: 52f8da66-fe8e-46d7-9dde-6aafd84932d5
