# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
default:
  image:
    name: $DOCKER_HUB_PROXY/docker:27.0.1-cli
    pull_policy: always
  interruptible: false

include:
  - component: $CI_SERVER_FQDN/templates/components/publish/live@0.3.0
  - component: $CI_SERVER_FQDN/templates/components/publish/hub@0.3.0

  - component: $CI_SERVER_FQDN/templates/components/docker/amd64@0.9.5
    inputs:
      interruptible: false
      args: >-
        --build-context=certs=/builds/docker/docker.tmp
      healthcheck-uuid: cd8b11c8-8ec5-45a1-89b1-495c51d6c4aa

  - component: $CI_SERVER_FQDN/templates/components/docker/arm64@main
    rules:
      - if: $CI_COMMIT_TAG
        when: never
    inputs:
      interruptible: false
      args: >-
        --build-context=certs=/builds/docker/docker.tmp
      healthcheck-uuid: 23310f5b-19c1-47aa-a94b-66722cec170e

  - component: $CI_SERVER_FQDN/templates/components/docker/multi@main
    rules:
      - if: $CI_COMMIT_TAG
        when: never
    inputs:
      interruptible: false
      needs:
        - docker:amd64
        - docker:arm64
      args: >-
        --cache-from=type=registry,ref=${DOCKER_IMAGE_CACHE_PATH}:amd64
        --cache-from=type=registry,ref=${DOCKER_IMAGE_CACHE_PATH}:arm64
        --build-context=certs=/builds/docker/docker.tmp
      healthcheck-uuid: 52f8da66-fe8e-46d7-9dde-6aafd84932d5

  - component: $CI_SERVER_FQDN/templates/components/docker/multi@main
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      name: release
      interruptible: false
      args: >-
        --cache-from=type=registry,ref=${DOCKER_IMAGE_CACHE_PATH}:latest
        --build-context=certs=/builds/docker/docker.tmp
      tag: $HARBOR_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_TAG
      tags: >-
        --tag=$HARBOR_REGISTRY_LIVE/$CI_PROJECT_PATH:$CI_COMMIT_TAG
      healthcheck-uuid: 52f8da66-fe8e-46d7-9dde-6aafd84932d5
