default:
  image: registry.timmertech.nl/docker/docker:latest

stages:
  - build
  - multi
  - dockerhub
  - trigger

include:
  - project: templates/ci
    file: docker.yml

amd64:
  extends: .docker-build-amd64

arm64:
  extends: .docker-build-arm64

multi:
  extends: .docker-build-multi
  stage: multi
  variables:
    PLATFORM: "linux/arm64,linux/amd64"

dockerhub:
  extends: .docker-build-multi
  stage: dockerhub
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_IMAGE: ${DOCKER_IMAGE_HUB}
