stages:
  - build
  - dockerhub

include:
  - project: templates/ci
    file: docker-multi-arch.yml

build:
  extends: .docker-multi-arch-build

dockerhub:
  stage: dockerhub
  extends: .docker-multi-arch-build
  variables:
    DOCKER_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest
  only:
    - main
    - schedules
