# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
default:
  image:
    name: $DOCKER_HUB_PROXY/docker:27.0.1-cli
    pull_policy: always
  interruptible: false

include:
  - component: $CI_SERVER_FQDN/templates/components/workflow/default@0.4.0
  - component: $CI_SERVER_FQDN/templates/components/publish/live@0.6.0
  - component: $CI_SERVER_FQDN/templates/components/publish/hub@0.6.0

  - component: $CI_SERVER_FQDN/templates/components/docker/amd64@1.3.5
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
    inputs:
      interruptible: false
      args: >-
        --build-context=gitlab=/builds/$CI_PROJECT_PATH.tmp
  - component: $CI_SERVER_FQDN/templates/components/docker/arm64@1.3.5
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
    inputs:
      interruptible: false
      args: >-
        --build-context=gitlab=/builds/$CI_PROJECT_PATH.tmp
  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.3.5
    rules:
      - if: $CI_COMMIT_TAG
        when: never
      - when: always
    inputs:
      interruptible: false
      needs:
        - docker:amd64
        - docker:arm64
      args: >-
        --cache-from=type=registry,ref=$DOCKER_IMAGE_CACHE_PATH:amd64
        --cache-from=type=registry,ref=$DOCKER_IMAGE_CACHE_PATH:arm64
        --build-context=gitlab=/builds/$CI_PROJECT_PATH.tmp
  - component: $CI_SERVER_FQDN/templates/components/docker/multi@1.3.5
    rules:
      - if: $CI_COMMIT_TAG
    inputs:
      name: release
      interruptible: false
      args: >-
        --cache-from=type=registry,ref=$DOCKER_IMAGE_CACHE_PATH:latest
        --build-context=gitlab=/builds/$CI_PROJECT_PATH.tmp
      tag: $HARBOR_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_TAG
      tags: >-
        --tag=$HARBOR_REGISTRY_LIVE/$CI_PROJECT_PATH:$CI_COMMIT_TAG
