default:
  image: gjrtimmer/docker:latest

stages:
  - build
  - multi

include:
  - project: templates/ci
    file: docker.yml

amd64:
  extends: .docker-build-amd64
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:amd64

arm64:
  extends: .docker-build-arm64
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:arm64

multi:
  extends: .docker-build-multi
  stage: multi
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:latest
