default:
  image: registry.timmertech.nl/docker/docker:latest

stages:
  - build
  - dockerhub
  - trigger

include:
  - project: templates/ci
    file: docker.yml

.build:
  extends: .docker-build-multi
  variables:
    PLATFORM: "linux/arm64,linux/amd64"

build:
  extends: .build

dockerhub:
  stage: dockerhub
  extends: .build
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_IMAGE: ${DOCKER_IMAGE_HUB}
