# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
default:
  image:
    name: $DOCKER_HUB_PROXY/docker:27.0.1-cli
    pull_policy: always
  interruptible: false

include:
  - component: $CI_SERVER_FQDN/templates/components/publish/live@main
  - component: $CI_SERVER_FQDN/templates/components/publish/hub@main

  - component: $CI_SERVER_FQDN/templates/components/docker/amd64@0.9.5
    inputs:
      interruptible: false
      args: >-
        --build-context=certs=/builds/docker/docker.tmp
        --build-arg=LOCAL_CA=${LOCAL_ROOT_CA}
        --build-arg=LOCAL_INTERMEDIATE_CA=${LOCAL_TURING_PI_CA}
        --build-arg=HARBOR_CERT=${HARBOR_CERT}
      healthcheck-uuid: cd8b11c8-8ec5-45a1-89b1-495c51d6c4aa

  - component: $CI_SERVER_FQDN/templates/components/docker/arm64@0.9.5
    inputs:
      interruptible: false
      args: >-
        --build-context=certs=/builds/docker/docker.tmp
        --build-arg=LOCAL_CA=${LOCAL_ROOT_CA}
        --build-arg=LOCAL_TURING_PI_CA=${LOCAL_TURING_PI_CA}
        --build-arg=HARBOR_CERT=${HARBOR_CERT}
      healthcheck-uuid: 23310f5b-19c1-47aa-a94b-66722cec170e

  - component: $CI_SERVER_FQDN/templates/components/docker/multi@0.9.5
    inputs:
      interruptible: false
      needs:
        - docker:amd64
        - docker:arm64
      args: >-
        --cache-from=type=registry,ref=${DOCKER_IMAGE_CACHE_PATH}:amd64
        --cache-from=type=registry,ref=${DOCKER_IMAGE_CACHE_PATH}:arm64
        --build-context=certs=/builds/docker/docker.tmp
        --build-arg=LOCAL_CA=${LOCAL_ROOT_CA}
        --build-arg=LOCAL_INTERMEDIATE_CA=${LOCAL_TURING_PI_CA}
        --build-arg=HARBOR_CERT=${HARBOR_CERT}
      healthcheck-uuid: 52f8da66-fe8e-46d7-9dde-6aafd84932d5
