image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest

stages:
  - build
  - deploy

include:
  - project: templates/ci
    file: docker.yml
  - project: templates/ci
    file: docker-auth-hub.yml
  - project: templates/ci
    file: docker-multi-arch.yml

################################################################################
# Job Configuration
################################################################################
build:
  extends: .docker-multi-arch-build

dockerhub:
  stage: deploy
  extends: .docker-multi-arch-build
  variables:
    DOCKER_IMAGE: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest
  only:
    - main
    - schedules
