default:
  image: 
    name: gjrtimmer/docker:latest
    pull_policy: always
  interruptible: false

stages:
  - build
  - multi

include:
  - project: templates/ci
    file: docker.yml

amd64:
  extends: .docker-build-amd64
  interruptible: false
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:amd64

arm64:
  extends: .docker-build-arm64
  interruptible: false
  variables:
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:arm64

multi:
  extends: .docker-build-multi
  interruptible: false
  stage: multi
  variables:
    PLATFORM: "linux/arm64,linux/amd64"
    DOCKER_HUB: "ENABLED"
    DOCKER_ARGS: >-
      --cache-from=type=registry,ref=${DOCKER_IMAGE}
      --cache-from=type=registry,ref=${DOCKER_IMAGE_PATH}:amd64
      --cache-from=type=registry,ref=${DOCKER_IMAGE_PATH}:arm64
    DOCKER_TAGS: >-
      --tag=${DOCKER_IMAGE_HUB_PATH}:latest
