image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest

stages:
  - build
  - trigger

include:
  - project: templates/ci
    file: docker.yml
  - project: templates/ci
    file: dockerhub.yml

################################################################################
# Job Configuration
################################################################################
build:
  stage: build
  interruptible: true
  only:
    - master
    - schedules
  script:
    - docker build --pull
      --build-arg VCS_REF="${CI_COMMIT_SHORT_SHA}"
      --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
      --build-arg CI_PROJECT_NAME=${CI_PROJECT_NAME}
      --build-arg CI_PROJECT_URL="${CI_PROJECT_URL}"
      --build-arg DOCKER_PROXY=${DOCKER_PROXY_HOST}
      --build-arg DOCKER_IMAGE=${DOCKER_IMAGE}
      --file=${DOCKER_FILE}
      --tag=${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

dockerhub:
  stage: deploy
  extends: .dockerhub
  variables:
    DOCKER_IMAGE_HUB: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:latest
  only:
    - master
    - schedules
